#!/bin/bash
ytdl="yt-dlp"

source .config/ytlib.conf.dist
[ -e '.config/ytlib.conf' ] && source .config/ytlib.conf

if [ "$1" = "" ]; then
    echo "$0: nothing specified"
    exit 1
fi

cd `dirname $0`

echo "----
begin ytlib run
 $(date)
 args: $@
" >> .ytlib.log

$ytdl --config-location ".internal/ytdl.conf" "$@"
