#!/bin/bash

videodir="$1"
if ! [ -e "$videodir/.ffmeta" ]; then
    echo '[add-meta] adding metadata...'
    jq --raw-output 'def esc: . | split("") | map({"\\": "\\\\", "\n": "\\\n", ";": "\\;", "#": "\\#", "=": "\\="}[.] // .) | join("");
";FFMETADATA1\nTITLE=\(.fulltitle | esc)\nARTIST=\(.channel | esc)\n",
(.chapters[] | "[CHAPTER]\nTIMEBASE=1/1000\nSTART=\(.start_time * 1000)\nEND=\(.end_time * 1000)\nTITLE=\(.title | esc)\n")' "$videodir/video.info.json" > "$videodir/.ffmeta"
    ffmpeg -i "$videodir/video.mkv" -i "$videodir/.ffmeta" -map_metadata 1 -codec copy "$videodir/video.withmeta.mkv" -y && mv "$videodir/video.withmeta.mkv" "$videodir/video.mkv"
    echo '[add-meta] metadata added to video file'
else
    echo '[add-meta] metadata already added'
fi
