#!/bin/bash

for path in "$@"; do
	[ -f "$path" ] && path=`dirname "$path"`
	echo "$path:"
	.internal/getinfojson "$path" | jq '" title: \(.fulltitle)
 channel: \(.channel)
 \(.like_count) likes, \(.dislike_count) dislikes, \(.view_count) views
 duration: \(.duration | strftime("%H:%M:%S"))
 tags: \(if (.tags // []) == [] then "<none>" else .tags | join(", ") end)
 subtitles: \(if (.subtitles // {}) == {} then "<none>" else .subtitles | keys | join(", ") end)
 format: \(.format)
         \(.width)x\(.height) @ \(.fps) FPS, \(.ext)
 original URL: \(.webpage_url)"'\
	--raw-output
done
