#!/bin/bash

if [ "$1" = "-h" ]; then
    echo "$0: get a random video from a random channel"
    echo "usage: $0 [-h] [-n]"
    echo ' -h: display this message'
    echo ' -d: get the directory, not the video'
    exit
fi

video=`shuf -n 1 .db/index.txt | awk '{print $NF}'`

if [ "$1" = "-d" ]; then
    echo `dirname "$video"`
else
    echo "$video"
fi

