#!/bin/bash

source .config/ytlib.conf.dist
[ -e 'ytlib.conf' ] && source ytlib.conf

if [ "$1" = "-h" ]; then
    echo "$0 [-h] [-f]"
    echo ' -h: display this message'
    echo ' -f: only print filename and exit'
    echo 'set $PLAYER to change the video player'
    exit
fi

if [ ! -f "$INDEXDB" ]; then
    echo "* index not present at '$INDEXDB'. use update-cache"
    exit
fi

fzfargs=( )
[ "$SEARCHSORT" = "0" ] && fzfargs+=("--no-sort" "--tac")
! [ "$SEARCHPREVIEW" = "0" ] && fzfargs+=("--preview" 'utils/.search-preview {}')
selected=`fzf "${fzfargs[@]}" < "$INDEXDB"`
selected_file=`echo -n "$selected" | awk '{print $(NF)}'`

[ -z "$selected_file" ] && exit

if [ "$1" = "-f" ]; then
    echo "$selected_file"
elif [ "$1" = "-d" ]; then
    echo `dirname "$selected_file"`
else
    printf -v player_cmd "$PLAYER" "$selected_file"
    eval "$player_cmd"
fi
